### PR TITLE
Adding BehaviorSubject instead of a normal StreamController

### LINKED ISSUE #3: I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 236 pos 16: 'indexOf(child) > index': is not true.
When I added more than 7 items,  and I slide down the list and slide up, it shows an error

image

I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.

### PR DESCRIPTION
**Pull request by RobertBrunhage**
Resolved #3 by using a `BehaviorSubject` so the `stream` can be listened to multiple times and also remember the last value that was pushed out the `stream`.

### CODE REVIEW

**Comment by amoslai5128** [comment]
> Resolved #3 by using a `BehaviorSubject` so the `stream` can be listened to multiple times and also remember the last value that was pushed out the `stream`.

Thank you for the replying, I've done some research on the internet, is the RxDart only way to deal with this problem? I've seen many different methods like Bloc, MobX, Reduce, and said RxDart. 

What should I learn as a newbie to this flutter world?  I don't want to trip into the inherent weight again,  it makes me like a fool... I think life can be easier, doesn't it? 

Thanks again, I'll be very happy if you can reply to me.

**Comment by amoslai5128** [comment]
And also, I've another question but not very related to your video,  should there be any way that can merge and two document snapshots (from nested streamBuilder) together into a single one snapshot that can use .map((doc) => doc.document.xxx ]).toList()?  

This problem comes up when I'm using the Firestore to have two collections and some data are related.

**Comment by RobertBrunhage** [comment]
> > Resolved #3 by using a `BehaviorSubject` so the `stream` can be listened to multiple times and also remember the last value that was pushed out the `stream`.
> 
> Thank you for the replying, I've done some research on the internet, is the RxDart only way to deal with this problem? I've seen many different methods like Bloc, MobX, Reduce, and said RxDart.
> 
> What should I learn as a newbie to this flutter world? I don't want to trip into the inherent weight again, it makes me like a fool... I think life can be easier, doesn't it?
> 
> Thanks again, I'll be very happy if you can reply to me.

In my experience when you are working with streams `RxDart` is the way to go but I can be wrong.

I am in the process of learning all the state management solutions so won't give a final answer yet but I believe `Provider` and `MobX` should be a pretty good combo for beginners.



> And also, I've another question but not very related to your video, should there be any way that can merge and two document snapshots (from nested streamBuilder) together into a single one snapshot that can use .map((doc) => doc.document.xxx ]).toList()?
> 
> This problem comes up when I'm using the Firestore to have two collections and some data are related.

This becomes a bit more complex most of the times as you will use RxDart to combine them, you can find an example of me combining streams here: https://github.com/RobertBrunhage/water_reminder_app_youtube/blob/0fe3e60959ad2fea7ff0723fa520d459b427233e/lib/src/widgets/buttons/circle_water_button.dart#L129-L134

Hope this clears up some of the things for you. As I said (as of typing this) I am in the process of learning all the different state management solutions and is livestreaming it, so be sure to check those out and maybe you can find a good solution out of them yourself also :)

**Comment by amoslai5128** [comment]
> > > Resolved #3 by using a `BehaviorSubject` so the `stream` can be listened to multiple times and also remember the last value that was pushed out the `stream`.
> > 
> > 
> > Thank you for the replying, I've done some research on the internet, is the RxDart only way to deal with this problem? I've seen many different methods like Bloc, MobX, Reduce, and said RxDart.
> > What should I learn as a newbie to this flutter world? I don't want to trip into the inherent weight again, it makes me like a fool... I think life can be easier, doesn't it?
> > Thanks again, I'll be very happy if you can reply to me.
> 
> In my experience when you are working with streams `RxDart` is the way to go but I can be wrong.
> 
> I am in the process of learning all the state management solutions so won't give a final answer yet but I believe `Provider` and `MobX` should be a pretty good combo for beginners.
> 
> > And also, I've another question but not very related to your video, should there be any way that can merge and two document snapshots (from nested streamBuilder) together into a single one snapshot that can use .map((doc) => doc.document.xxx ]).toList()?
> > This problem comes up when I'm using the Firestore to have two collections and some data are related.
> 
> This becomes a bit more complex most of the times as you will use RxDart to combine them, you can find an example of me combining streams here: https://github.com/RobertBrunhage/water_reminder_app_youtube/blob/0fe3e60959ad2fea7ff0723fa520d459b427233e/lib/src/widgets/buttons/circle_water_button.dart#L129-L134
> 
> Hope this clears up some of the things for you. As I said (as of typing this) I am in the process of learning all the different state management solutions and is livestreaming it, so be sure to check those out and maybe you can find a good solution out of them yourself also :)

WoW, I'll try it tmr, thank you for sharing me so many details...  !!!

Also, I've another question about the correct way using of Firestore, **I think I was wrong to use it?** 
In my case, I currently have **two** collections, which are **EventRecords** & **UserInfo**. EventRecords stores all the history of a user while UserInfo stores the user's Icon path, user nickname, background...

Should there be only **one** collection and each document is for a user, then the subcollections all are a user's data things?

Top collection (App) ---> Document (each userID) ----> subcollection (each user's func/activities) ---> xxx

That's all my idea, what do you think?

**Comment by RobertBrunhage** [comment]
> Also, I've another question about the correct way using of Firestore, **I think I was wrong to use it?**
> In my case, I currently have **two** collections, which are **EventRecords** & **UserInfo**. EventRecords stores all the history of a user while UserInfo stores the user's Icon path, user nickname, background...
> 
> Should there be only **one** collection and each document is for a user, then the subcollections all are a user's data things?
> 
> Top collection (App) ---> Document (each userID) ----> subcollection (each user's func/activities) ---> xxx
> 
> That's all my idea, what do you think?


It depends on how you would query as top level query is little more flexible than subcollections. But most of the times I just create a Top collection (users) --> user document (userId) => subcollections (same as you did).

If that doesn't suit your needs for the application than you can reorganize it. noSQL is a little different that way as you structure it in the way you query, which you doesn't really do with SQL.

Just a heads up: with noSQL databases such as Firestore there is nothing wrong with dublicating data either :)

**Comment by amoslai5128** [comment]
> > Also, I've another question about the correct way using of Firestore, **I think I was wrong to use it?**
> > In my case, I currently have **two** collections, which are **EventRecords** & **UserInfo**. EventRecords stores all the history of a user while UserInfo stores the user's Icon path, user nickname, background...
> > Should there be only **one** collection and each document is for a user, then the subcollections all are a user's data things?
> > Top collection (App) ---> Document (each userID) ----> subcollection (each user's func/activities) ---> xxx
> > That's all my idea, what do you think?
> 
> It depends on how you would query as top level query is little more flexible than subcollections. But most of the times I just create a Top collection (users) --> user document (userId) => subcollections (same as you did).
> 
> If that doesn't suit your needs for the application than you can reorganize it. noSQL is a little different that way as you structure it in the way you query, which you doesn't really do with SQL.
> 
> Just a heads up: with noSQL databases such as Firestore there is nothing wrong with dublicating data either :)

OK, got it, I'll do like that next project.
Speaking of which, I've just seen there is a flutter_bloc in Pub.dev, it looks a little different between normal BloC?    check it out: https://pub.dev/packages/flutter_bloc
I'm very looking forward to seeing you doing the lecture/ livestreaming for lastest Bloc!!!

**Pull request merged**
